# 环境配置
spring:
  profiles:
    active: dev

# mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.luoxj.springbootscaffold.entity

# thymeleaf 配置
thymeleaf:
  cache: false





